export const category_channels = [
  {
    category: "tools",
    channels: [
      "audio-tools",
      "career-tools",
      "developer-tools",
      "discord-tools",
      "educational-tools",
      "file-tools",
      "facebook-tools",
      "gaming-tools",
      "general-tools",
      "image-tools",
      "internet-tools",
      "reddit-tools",
      "search-tools",
      "system-tools",
      "telegram-tools",
      "text-tools",
      "twitch-tools",
      "twitter-tools",
      "url-tools",
      "video-tools",
      "youtube-tools",
    ],
  },
  {
    category: "miscellaneous",
    channels: [
      "browser-games",
      "cooking",
      "extensions",
      "fonts",
      "fun-sites",
      "health",
      "indexes",
      "maps",
      "media-databases",
      "news",
      "non-english",
      "piracy-discussion",
      "request-media",
      "subtitles",
    ],
  },
  {
    category: "reading",
    channels: [
      "audiobooks",
      "comics",
      "ebook-readers",
      "educational",
      "general",
      "light-novels",
      "manga",
      "magazines",
      "religion-esoteric",
      "newspapers",
    ],
  },
  {
    category: "android_ios",
    channels: [
      "android-adblocking",
      "android-audio",
      "android-emulators",
      "android-general",
      "android-privacy",
      "android-reading",
      "android-torrenting",
      "android-video",
      "ios-adblocking",
      "ios-audio",
      "ios-general",
      "ios-jailbreaking",
      "ios-privacy",
      "ios-torrenting",
      "ios-reading",
      "ios-video",
    ],
  },
  {
    category: "downloading",
    channels: [
      "anime",
      "arcade-retro",
      "educational",
      "emulators-roms",
      "games",
      "general",
      "movies-tv",
      "music",
      "software",
      "usenet",
    ],
  },
  {
    category: "torrenting",
    channels: [
      "anime",
      "educational",
      "games",
      "general",
      "movies-tv",
      "music",
      "torrent-clients",
    ],
  },
  {
    category: "linux_macos",
    channels: [
      "linux-adblock-privacy",
      "linux-gaming",
      "linux-general",
      "linux-software",
      "mac-adblock-privacy",
      "mac-gaming",
      "mac-general",
      "mac-software",
    ],
  },
  {
    category: "streaming",
    channels: [
      "ambient-relaxation",
      "anime",
      "educational",
      "movies-tv",
      "live-tv",
      "podcasts-radio",
      "music",
      "sports",
    ],
  },
  {
    category: "adblock_privacy",
    channels: ["adblocking", "antivirus", "dns", "privacy", "proxies", "vpn"],
  },
];
export const resources = [
  {
    link: "/resource/adblock-vpn-privacy",
    emoji: "📛",
    title: "Adblock, Privacy, Antivirus",
  },
  {
    link: "/resource/video",
    emoji: "📺",
    title: "Movies, TV, Anime, Sports",
  },
  {
    link: "/resource/audio",
    emoji: "🎵",
    title: " Music, Podcasts, Radio ",
  },
  { link: "/resource/games", emoji: "🎮", title: "Gaming, Emulation" },
  {
    link: "/resource/reading",
    emoji: "📗",
    title: "Books, Comics, Manga",
  },
  { link: "/resource/download", emoji: "💾", title: "Downloading" },
  { link: "/resource/torrent", emoji: "🌀", title: "Torrenting" },
  { link: "/resource/edu", emoji: "🧠", title: "Educational" },
  { link: "/resource/tools-misc", emoji: "🔧", title: "Tools" },
  { link: "/resource/misc", emoji: "📂", title: "Miscellaneous" },
  { link: "/resource/android", emoji: "📱", title: "Android, iOS" },
  { link: "/resource/linux", emoji: "🐧", title: "Linux, MacOS" },
  { link: "/resource/storage", emoji: "📦", title: "Storage" },
  { link: "/resource/non-eng", emoji: "🌍", title: "Non English" },
  { link: "/resource/base64", emoji: "🔗", title: "Base 64" },
];
